src/TfsTimeline/Controllers/BuildsApiController.cs
using System;
using System.Linq;
using System.Web.Mvc;
using System.Web.UI;

using Greenicicle.TfsTimeline.Models;

namespace Greenicicle.TfsTimeline.Controllers
{
    public class BuildsApiController : Controller
    {
        private readonly IBuildService buildService;

        public BuildsApiController(IBuildService buildService)
        {
            this.buildService = buildService;
        }

        [HttpPost]
        [OutputCache(Duration = 360, Location = OutputCacheLocation.Server)]
        public ActionResult ProjectNames()
        {
            var projectNames = buildService.GetProjects();

            var result = new
            {
                Self = Url.Action("ProjectNames"),
                Projects = projectNames.Select(projectName => new
                {
                    Name = projectName,
                    Url = Url.Action("BuildNames", new { projectName }),
                })
            };

            return Json(result);
        }

        [HttpPost]
        [OutputCache(Duration = 360, Location = OutputCacheLocation.Server)]
        public ActionResult BuildNames(string projectName)
        {
            var buildNames = buildService.GetBuildDefinitions(projectName);

            var result = new
            {
                Self = Url.Action("BuildNames", new { projectName }),
                Projects = buildNames.Select(buildName => new
                {
                    Name = buildName,
                    Url = Url.Action("BuildTimeline", new { projectName, buildName }),
                })
            };

            return Json(result);
        }

        [HttpPost]
        [OutputCache(Duration = 15, Location = OutputCacheLocation.Server)]
        public ActionResult BuildTimeline(string projectName, string buildName, string sinceThisTime)
        {
            DateTime minBuildAge;

            if (!DateTime.TryParse(sinceThisTime, out minBuildAge))
            {
                minBuildAge = DateTime.Today;
            }

            var builds = buildService.GetBuilds(projectName, buildName, minBuildAge)
                .OrderBy(b => b.StartedAt)
                .ToList();

            DateTime? lastFinished = minBuildAge;
            if (builds.Any())
            {
               lastFinished = builds
                  .Where(b => b.Status == BuildStatus.Failed.ToString() || b.Status == BuildStatus.Succeeded.ToString())
                  .Select(b => b.FinishedAt)
                  .OrderByDescending(finished => finished)
                  .FirstOrDefault();
            }

            if (lastFinished == null)
            {
                lastFinished = DateTime.Today;
            }

            var lastFinishedParam = lastFinished.Value.ToString("dd-MM-yyyy HH:mm:ss");

            var buildTimeline = new
            {
                Self = Url.Action("BuildTimeline", new { projectName, buildName }),
                Refresh = Url.Action("BuildTimeline", new { projectName, buildName, sinceThisTime = lastFinishedParam }),
                Builds = builds
            };

            return Json(buildTimeline);
        }
    }
}

src/TfsTimeline/Controllers/BuildsController.cs
using System.Linq;
using System.Web.Mvc;

using Greenicicle.TfsTimeline.Models;
using Greenicicle.TfsTimeline.ViewModels;

namespace Greenicicle.TfsTimeline.Controllers
{
    public class BuildsController : Controller
    {
        private readonly IBuildService buildService;

        public BuildsController(IBuildService buildService)
        {
            this.buildService = buildService;
        }

        public ActionResult ProjectNamesView()
        {
            var projectNames = buildService.GetProjects();

            var viewModel = new LinkListViewModel
            {
                Title = "Projects on TFS",
                Links = projectNames.ToDictionary(
                    projectName => Url.Action("BuildNamesView", new { projectName }),
                    projectName => projectName)
            };

            return View("LinkListView", viewModel);
        }
        
        public ActionResult BuildNamesView(string projectName)
        {
            var buildNames = buildService.GetBuildDefinitions(projectName);

            var viewModel = new LinkListViewModel
            {
                Title = string.Format("Builds for project {0}", projectName),
                Links = buildNames.ToDictionary(
                    buildName => Url.Action("BuildTimelineView", new { projectName, buildName }),
                    buildName => buildName)
            };

            return View("LinkListView", viewModel);
        }

        public ActionResult BuildTimelineView(string projectName, string buildName)
        {
            return View(new LatestBuildsViewModel { ProjectName = projectName, BuildName = buildName });
        }
    }
}

src/TfsTimeline/Views/Builds/BuildTimelineView.cshtml
@model Greenicicle.TfsTimeline.ViewModels.LatestBuildsViewModel
@{
    ViewBag.Title = Model.ProjectName + "Builds";
}
<script type="text/javascript" src="@Url.Content("~/Scripts/tfs-timeline.viewmodel.build.js")"></script>
<script type="text/javascript">
    $(function () {
        var ciBuildServiceUrl = '@Url.Action("BuildTimeline", "BuildsApi", new { projectName = Model.ProjectName, buildName = Model.BuildName })';
        tfsTimeline.buildsViewModel = new tfsTimeline.BuildsViewModel(ciBuildServiceUrl);
        ko.applyBindings(tfsTimeline.buildsViewModel);
        tfsTimeline.buildsViewModel.refresh();
        tfsTimeline.buildsViewModel.updateBuildDuration(new Date());
    });
</script>
<h2 data-bind="visible:isLoading" style="text-align: center">::: Loading :::</h2>

<div data-bind="foreach: { data: builds, afterAdd: handleAfterAdd }"
    ><div style="display:none;" data-bind="attr: { class: Status }">
        <div style="margin-bottom: 10px;">
            <span style="font-weight: bold" data-bind="text: TriggeredBy"></span>
            <span class="Weak" data-bind="text: startedAtTime"></span>
        </div>
        <div style="margin-bottom: 10px" data-bind="visible: CheckinComments">
            &quot;<span data-bind="text: CheckinComments"></span>&quot; 
            <span class="Weak" data-bind="text: WorkItemTitles"></span>
        </div>
        <div>
            <span data-bind="visible:isRunning">
                ::: Running
                <span class="Neutral" data-bind="text: runDurationMinutes"></span>
            </span>

            <span data-bind="visible:TestsTotal">
                ::: Tests 
                <span class="Neutral" data-bind="text: TestsTotal"></span> 
                <span  class="Good" data-bind="text: TestsPassed"></span> 
                <span  class="Bad" data-bind="text: TestsFailed"></span>
            </span>    
                
            <span data-bind="visible:showFxCop">
                ::: FxCop
                <span  class="Bad" data-bind="text: CodeAnalysisErrors"></span>
                <span  class="Warn" data-bind="text: CodeAnalysisWarnings"></span>
            </span>
            :::
        </div>
</div></div>
